version: '2.1'
services:

  postgres:
    container_name: db
    image: postgres:latest
    environment:
      - POSTGRES_USER=mybatis
      - POSTGRES_PASSWORD=iova
      - POSTGRES_DB=mybatis
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - custom-network
    volumes:
      - ./dbdata/vol:/var/lib/postgresql/data:rw
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  article-server:
    container_name: article-server
    build:
      dockerfile: Dockerfile
    environment:
      - com.iova.mybatis.postgres.url=jdbc:postgresql://db:5432/postgres
    depends_on:
      postgres:
        condition: service_started
    image: article-server:latest
    ports:
      - "8888:8888"
    networks:
      - custom-network

networks:
  custom-network:
    driver: bridge