version: '3.1'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=mybatis
      - POSTGRES_PASSWORD=iova
      - POSTGRES_DB=mybatis
      - PGDATA=/var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - ./dbdata/vol:/var/lib/postgresql/data:rw
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  vol:
    driver: local