version: '3.1'
services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=mybatis
      - POSTGRES_PASSWORD=iova
      - POSTGRES_DB=mybatis
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql